FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_CALCULATOR_API_BASE_URL
ARG VITE_AUTH_API_BASE_URL
ARG VITE_CONTACT_API_BASE_URL
ARG VITE_NOTES_API_BASE_URL
ARG VITE_API_BASE_URL

ENV VITE_CALCULATOR_API_BASE_URL=$VITE_CALCULATOR_API_BASE_URL
ENV VITE_AUTH_API_BASE_URL=$VITE_AUTH_API_BASE_URL
ENV VITE_CONTACT_API_BASE_URL=$VITE_CONTACT_API_BASE_URL
ENV VITE_NOTES_API_BASE_URL=$VITE_NOTES_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build


FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
